### ISSUE TITLE
Feature Request: Implement /leagues-by-date?date=eq.{date} endpoint from SportDevs API

### ISSUE THREAD

**Issue by riciminerson** [blackwater17/iptv-football-app#1]
Hey there! I noticed that the IPTV Football App could benefit from displaying football events by date. To enhance the user experience, I suggest implementing the /leagues-by-date?date=eq.{date} endpoint from the SportDevs API. This will allow users to easily discover upcoming football events based on a specific date. To implement this feature, you can create a new function in the codebase that fetches data from the SportDevs API using the specified endpoint and displays the information in a user-friendly format on the app interface. I believe this addition will provide users with more flexibility and convenience when exploring football events. Looking forward to seeing this feature added to the repository! Cheers!

**Comment by blackwater17** [comment]
Closed as this appears to be a ChatGPT-generated post from a bot account.
